resources:
- name: often
  type: time
  source: {interval: 1m}

jobs:
- name: hello-world
  plan:
  - get: often
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image: "docker:///ubuntu"
      run:
        path: echo
        args: ["Hello, world!"]

